version: "2"

linters:
  disable:
    - dupl
    - gocyclo
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nilnil
    - noctx
    - prealloc
    - staticcheck

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      severity: warning
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - wrapperFunc
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    generated: strict
    presets: []
    rules:
      # Allow password/access token fields in API schemas
      - linters:
          - gosec
        text: "G117"

      # Temp file operations from os.CreateTemp are safe
      - linters:
          - gosec
        text: "G703"

      # User's editor choice is intentional
      - linters:
          - gosec
        text: "G702"

      # API client making requests to configured endpoints
      - linters:
          - gosec
        text: "G704"

      # Ignore error return on Close
      - text: "Error return value of `.*Close` is not checked"
        linters:
          - errcheck

      # Ignore err shadow in defer
      - text: 'shadow: declaration of "err"'
        source: "defer "
        linters:
          - govet
