// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Class struct {
	ClassID     int64
	ClusterID   int64
	Name        string
	Description sql.NullString
}

type Cluster struct {
	ClusterID   int64
	Name        string
	Description sql.NullString
}

type Exercise struct {
	ExerciseID  int64
	ProjectUuid string
	GroupID     int64
	Name        string
	State       sql.NullString
	CreatedAt   sql.NullTime
}

type Group struct {
	GroupID int64
	ClassID int64
	Name    string
}

type GroupAssignment struct {
	GroupID    int64
	NodeID     int64
	AssignedAt sql.NullTime
}

type Node struct {
	NodeID    int64
	ClusterID int64
	Protocol  string
	AuthUser  string
	Host      string
	Port      int64
	Weight    int64
	MaxGroups sql.NullInt64
}

type User struct {
	UserID          int64
	Username        string
	FullName        sql.NullString
	GroupID         int64
	DefaultPassword string
}
